# ruby encoding: utf-8

# CICLO BÁSICO DE ENGENHARIA
course_eng = VagasRemanescentesCourse.create(name: 'CICLO BÁSICO DE ENGENHARIA')
VagasRemanescentesClass.create([
  { name: 'POLO ARAÇATUBA – 4T', vagas_remanescentes_course: course_eng },
  { name: 'POLO ARARAS – 3N', vagas_remanescentes_course: course_eng },
  { name: 'POLO ARARAS – 5N', vagas_remanescentes_course: course_eng },
  { name: 'POLO ARARAS – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO BARUERI – 3N', vagas_remanescentes_course: course_eng },
  { name: 'POLO BARUERI – 5N', vagas_remanescentes_course: course_eng },
  { name: 'POLO BARUERI – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO CAPÃO BONITO – 5T', vagas_remanescentes_course: course_eng },
  { name: 'POLO CRUZEIRO – 6T', vagas_remanescentes_course: course_eng },
  { name: 'POLO DIADEMA – 2N', vagas_remanescentes_course: course_eng },
  { name: 'POLO DIADEMA – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO ITAPETININGA – 2N', vagas_remanescentes_course: course_eng },
  { name: 'POLO ITAPETININGA – 4N', vagas_remanescentes_course: course_eng },
  { name: 'POLO ITAPETININGA – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO ITU – 6T', vagas_remanescentes_course: course_eng },
  { name: 'POLO JALES – 6T', vagas_remanescentes_course: course_eng },
  { name: 'POLO JALES – ST', vagas_remanescentes_course: course_eng },
  { name: 'POLO JAÚ – 2N', vagas_remanescentes_course: course_eng },
  { name: 'POLO JAÚ – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO JUNDIAÍ – 4T', vagas_remanescentes_course: course_eng },
  { name: 'POLO PINDAMONHANGABA – ST', vagas_remanescentes_course: course_eng },
  { name: 'POLO SANTO ANDRÉ – 4T', vagas_remanescentes_course: course_eng },
  { name: 'POLO SANTOS – 3N', vagas_remanescentes_course: course_eng },
  { name: 'POLO SANTOS – 5N', vagas_remanescentes_course: course_eng },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – PARQUE – 2N', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – PARQUE – 4N', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – PARQUE – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO PAULO – ÁGUA AZUL – SM', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO PAULO – ÁGUA AZUL – ST', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO PAULO JAÇANÃ – 4N', vagas_remanescentes_course: course_eng },
  { name: 'POLO SÃO PAULO JAÇANÃ – SM', vagas_remanescentes_course: course_eng }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas básicas de Engenharia.
  { name: 'Administração I – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Cálculo I – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Cálculo II – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Cálculo III – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Ciência do Ambiente – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Ciência dos Materiais – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Economia – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Estatística – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Expressão Gráfica – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Fenômenos de Transporte – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Física I – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Física II – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Física III – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Geometria Analítica e Álgebra Linear – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Higiene e Segurança do Trabalho – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Informática – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Inglês – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Instalações Elétricas – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Introdução à Engenharia – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Matemática – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Mecânica Geral – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Metodologia Científica – 20h', vagas_remanescentes_course: course_eng },
  { name: 'Métodos Numéricos – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Produção de Textos – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Programação de Computadores – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Química – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Resistência dos Materiais – 40h', vagas_remanescentes_course: course_eng },
  { name: 'Sistemas de Informação – 80h', vagas_remanescentes_course: course_eng },
  { name: 'Sociedade e Cultura – 20h', vagas_remanescentes_course: course_eng }
])

# ENGENHARIA DE COMPUTAÇÃO
course_eng_comp = VagasRemanescentesCourse.create(name: 'ENGENHARIA DE COMPUTAÇÃO', parent: course_eng)
VagasRemanescentesClass.create([
  { name: 'POLO ARARAS – 2N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO ARARAS – 5N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO ARARAS – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO BARRETOS – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO DIADEMA – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO DIADEMA – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO FRANCA – 2N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO FRANCA – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO JAÚ – 4N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO JAÚ – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO JAÚ – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SANTOS – 2N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SANTOS – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – 2N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – CASA BLANCA – 4N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – JAÇANÃ – 3N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – JAÇANÃ – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – JAÇANÃ – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – JAMBEIRO – 4N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – JAMBEIRO – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – JAMBEIRO – 4N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – MENINOS – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – MENINOS – ST', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – PERA MARMELO – 2N', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – PERA MARMELO – SM', vagas_remanescentes_course: course_eng_comp },
  { name: 'POLO SP – PERA MARMELO – ST', vagas_remanescentes_course: course_eng_comp }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 800 horas de atividades em disciplinas básicas de Engenharia.
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas de Engenharia da Computação.
  { name: 'Bancos de Dados – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Circuitos Elétricos – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Circuitos Lógicos – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Computação Gráfica – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Controle e Automação – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Direito – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Eletrônica Aplicada – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Eletrônica Digital – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Eletrônica Embarcada – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Empreendedorismo e Gestão de Empresas – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Engenharia de Informação – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Engenharia de Software – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Engenharia Econômica – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Estratégia e Planejamento de Empresas – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Estruturas de Dados – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Fundamentos Matemáticos da Computação – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Gerência e Qualidade de Software – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Gestão de Projetos – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Inteligência Artificial – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Interfaces Humano-Computador – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Introdução aos Sistemas de Comunicação – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Linguagens e Compiladores – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Microeletrônica – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Modelos Probabilísticos para Computação – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Multimídia e Hipermídia – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Negócios online – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Organização de Computadores – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Programação Orientada a Objetos – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Projeto de Sistemas Computacionais – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Projeto Digital – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Projeto e Análise de Algoritmos – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Projeto e Programação de Jogos – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Propriedade Intelectual – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Redes de Computadores – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Segurança da Informação – 40h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Sistemas Distribuídos – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Sistemas Operacionais – 80h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Tecnologias de Comunicação de Dados – 60h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Tópicos Avançados em Eng. de Computação I – 20h', vagas_remanescentes_course: course_eng_comp },
  { name: 'Tópicos Avançados em Eng. de Computação II – 20h', vagas_remanescentes_course: course_eng_comp }
])

# ENGENHARIA DE PRODUÇÃO
course_eng_prod = VagasRemanescentesCourse.create(name: 'ENGENHARIA DE PRODUÇÃO', parent: course_eng)
VagasRemanescentesClass.create([
  { name: 'POLO ARARAS – 2N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO ARARAS – 5N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO ARARAS – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO BARRETOS – 4N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO BARRETOS – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO BARRETOS – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO DIADEMA – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO FRANCA – 2N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO FRANCA – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO FRANCA – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO JAÚ – 3N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO JAÚ – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – 2N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – CAMPO LIMPO – 4N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – CAMPO LIMPO – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – CAMPO LIMPO – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – CIDADE DUTRA – 5N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – CIDADE DUTRA – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – CIDADE DUTRA – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – JAÇANÃ – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – PARQUE SÃO CARLOS – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO ST – ROSA DA CHINA – 2N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO ST – ROSA DA CHINA – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO ST – ROSA DA CHINA – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – VILA ATLÃNTICA – 3N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO SP – VILA ATLÃNTICA – ST', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO TARUMÃ – 4N', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO TARUMÃ – SM', vagas_remanescentes_course: course_eng_prod },
  { name: 'POLO TARUMÃ – ST', vagas_remanescentes_course: course_eng_prod }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 800 horas de atividades em disciplinas básicas de Engenharia.
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas de Engenharia de Produção.
  { name: 'Administração II – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Automação Industrial – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Confiabilidade – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Controle Estatístico de Processo – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Direito – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Economia II – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Empreendedorismo – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Engenharia da Sustentabilidade – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Engenharia de Métodos – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Engenharia Econômica e Financeira – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Ergonomia – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Estratégia Organizacional e Marketing – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gerenciamento de Projetos – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão Ambiental – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão da Cadeia de Suprimento – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão da Informação – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão da Qualidade – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão da Tecnologia e da Inovação – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão de Contratos – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão de Custos – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão de Recursos Humanos – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão do Conhecimento – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Gestão Financeira e de Riscos – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Higiene e Segurança do Trabalho II – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Instalações Industriais – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Jogos de Empresa – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Logística – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Modelagem e Simulação – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Organização do Trabalho – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Organização Industrial – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Pesquisa Operacional I – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Pesquisa Operacional II – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Planejamento de Instalações – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Planejamento e Controle de Produção I – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Planejamento e Controle de Produção II – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Processos Industriais e Fabricação – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Projeto e Desenvolvimento do Produto – 80h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Psicologia e Sociologia do Trabalho – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Sistemas de Manutenção – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Sistemas de Produção – 40h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Tópicos Avançados em Engenharia de Produção I – 20h', vagas_remanescentes_course: course_eng_prod },
  { name: 'Tópicos Avançados em Engenharia de Produção II – 20h', vagas_remanescentes_course: course_eng_prod }
])

# LICENCIATURA EM BIOLOGIA
course_lic_bio = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM BIOLOGIA')
VagasRemanescentesClass.create([
  { name: 'POLO ITAPETININGA – ST', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO JALES – SM', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO JUNDIAÍ – 6T', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO JUNDIAÍ – SM', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO MOCOCA – SM', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO MOCOCA – ST', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO SANTOS – 4N', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO SANTOS – SM', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – 4N', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – SM', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – ST', vagas_remanescentes_course: course_lic_bio },
  { name: 'POLO TARUMÃ – SM', vagas_remanescentes_course: course_lic_bio }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 800 horas de atividades em disciplinas básicas de Licenciatura.
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas de Licenciatura em Biologia.
  { name: 'Bioquímica – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Células e Tecidos – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Corpo Humano: Órgãos e Sistemas – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Didática para Ciências e Biologia – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Ecologia – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Evolução – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Fisiologia Vegetal – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Genética – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Genética e Biologia Molecular – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Inglês Va – 20h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Inglês Vb – 20h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Inglês VIa – 20h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Inglês VIb – 20h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Microbiologia e Imunologia – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Morfologia Vegetal – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Parasitologia – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Planejamento para o Ensino de Biologia – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Práticas para o Ensino de Biologia I – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Práticas para o Ensino de Biologia II – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Práticas para o Ensino de Biologia III – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Práticas para o Ensino de Ciências – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Saneamento e Recuperação Ambientais – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Taxonomia Vegetal – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Tópicos Avançados em Biologia – 40h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Zoologia dos Invertebrados – 80h', vagas_remanescentes_course: course_lic_bio },
  { name: 'Zoologia dos Vertebrados – 80h', vagas_remanescentes_course: course_lic_bio }
])


# LICENCIATURA EM FÍSICA
course_lic_fis = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM FÍSICA')
VagasRemanescentesClass.create([
  { name: 'POLO DIADEMA – 2N', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO DIADEMA – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO ITU – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO ITU – ST', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO MOGI MIRIM – 6T', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO MOGI MIRIM – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO OSASCO – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO PINDAMONHANGABA – 6T', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO PINDAMONHANGABA – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SANTO ANDRÉ – 4T', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SANTO ANDRÉ – ST', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SÃO JOSÉ DO RIO PRETO – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SÃO JOSÉ DO RIO PRETO – ST', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SP – ÁGUA AZUL – 4N', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SP – JARDIM PAULISTANO – 5N', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SP – JARDIM PAULISTANO – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SP – TATUAPÉ – 6T', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SP – TATUAPÉ – SM', vagas_remanescentes_course: course_lic_fis },
  { name: 'POLO SP – TATUAPÉ – ST', vagas_remanescentes_course: course_lic_fis }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 800 horas de atividades em disciplinas básicas de Licenciatura.
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas de Licenciatura em Física.
  { name: 'Cálculo II – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Cálculo III para a Física – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Didática para Ciências e Física – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Eletromagnetismo – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Eletromagnetismo Avançado – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Estrutura da Matéria – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Física Matemática – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Física Quântica – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Geometria Analítica – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Inglês Va – 20h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Inglês Vb – 20h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Inglês VIa – 20h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Inglês VIb – 20h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Mecânica – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Mecânica Avançada – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Mecânica dos Fluidos – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Óptica – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Oscilações e Ondas – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Planejamento para o Ensino de Física – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Práticas para o Ensino de Ciências – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Práticas para o Ensino de Física I – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Práticas para o Ensino de Física II – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Práticas para o Ensino de Física III – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Teoria da Relatividade – 40h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Termodinâmica e Mecânica Estatística – 80h', vagas_remanescentes_course: course_lic_fis },
  { name: 'Tópicos Avançados em Física – 40h', vagas_remanescentes_course: course_lic_fis }
])


# LICENCIATURA EM MATEMÁTICA
course_lic_mat = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM MATEMÁTICA')
VagasRemanescentesClass.create([
  { name: 'POLO ARARAS – 3N', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO ARARAS – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO ARARAS – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO BARRETOS – 3N', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO BARRETOS – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO BARRETOS – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO CAPÃO BONITO – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO CAPÃO BONITO – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO CRUZEIRO – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO CRUZEIRO – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO INDAIATUBA – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO INDAIATUBA – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO JAÚ – 4N', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO JAÚ – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO JAÚ – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO JUNDIAÍ – 6T', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO SANTOS – 4N', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO SANTOS – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO SP – PARQUE VEREDAS – 5N', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO SP – PARQUE VEREDAS – SM', vagas_remanescentes_course: course_lic_mat },
  { name: 'POLO SP – PARQUE VEREDAS – ST', vagas_remanescentes_course: course_lic_mat }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 800 horas de atividades em disciplinas básicas de Licenciatura.
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas de Licenciatura em Matemática.
  { name: 'Álgebra Linear – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Cálculo II – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Cálculo III – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Cálculo IV – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Cálculo Numérico – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Didática para o Ensino de Matemática – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Elementos de Álgebra – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Estatística e Probabilidade – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Geometria Analítica – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Geometria Espacial – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Geometria Plana e Desenho Geométrico – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'História da Matemática – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Inglês Va – 20h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Inglês Vb – 20h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Inglês VIa – 20h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Inglês VIb – 20h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Lógica e Matemática Discreta – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Mecânica – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Planejamento para o Ensino de Matemática – 80h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Práticas para o Ensino de Matemática I – 40h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Práticas para o Ensino de Matemática II – 40h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Práticas para o Ensino de Matemática III – 40h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Práticas para o Ensino de Matemática IV – 40h', vagas_remanescentes_course: course_lic_mat },
  { name: 'Teoria dos Números – 80h', vagas_remanescentes_course: course_lic_mat }
])

# LICENCIATURA EM QUÍMICA
course_lic_qui = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM QUÍMICA')
VagasRemanescentesClass.create([
  { name: 'POLO ARAÇATUBA – 6T', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO ARAÇATUBA – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO FRANCA – 2N', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO FRANCA – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO FRANCA – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO ITU – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO ITU – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO MOGI MIRIM – 6T', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO MOGI MIRIM – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO OSASCO – 4M', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO OSASCO – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO PINDAMONHANGABA – 6T', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO PINDAMONHANGABA – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SANTO ANDRÉ – 4T', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SANTO ANDRÉ – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – BUTANTÃ – 4N', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – BUTANTÃ – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – BUTANTÃ – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – TATUAPÉ – 6T', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – TATUAPÉ – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – TATUAPÉ – ST', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – VILA CURUÇÁ – 2N', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – VILA CURUÇÁ – SM', vagas_remanescentes_course: course_lic_qui },
  { name: 'POLO SP – VILA CURUÇÁ – ST', vagas_remanescentes_course: course_lic_qui }
])
VagasRemanescentesActivity.create([
  # Você deve comprovar abaixo, no mínimo, 800 horas de atividades em disciplinas básicas de Licenciatura. 
  # Você deve comprovar abaixo, no mínimo, 400 horas de atividades em disciplinas de Licenciatura em Química.
  { name: 'Análise Instrumental – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Bioquímica – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Cálculo e Geometria Analítica – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Didática para Ciências e Química – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Elementos de Mineralogia – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Física Aplicada à Química – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Físico-Química I – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Físico-Química II – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'História e Filosofia da Química – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Inglês Va – 20h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Inglês Vb – 20h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Inglês VIa – 20h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Inglês VIb – 20h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Introdução à Química Quântica – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Metodologia para o Ensino de Química – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Pesquisa para o Ensino de Química – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Planejamento para o Ensino de Química – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Práticas para o Ensino de Ciências – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Práticas para o Ensino de Química I – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Práticas para o Ensino de Química II – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Práticas para o Ensino de Química III – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Química Analítica – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Química Experimental – 40h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Química Inorgânica – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Química Orgânica I – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Química Orgânica II – 80h', vagas_remanescentes_course: course_lic_qui },
  { name: 'Química, Sociedade e Cotidiano – 40h', vagas_remanescentes_course: course_lic_qui }
])
