# ruby encoding: utf-8

# CICLO BÁSICO DE ENGENHARIA
course = VagasRemanescentesCourse.create(name: 'CICLO BÁSICO DE ENGENHARIA')
VagasRemanescentesClass.create([
  { name: 'POLO ARAÇATUBA – 4T', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – 3N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – 5N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – SM', vagas_remanescentes_course: course },
  { name: 'POLO BARUERI – 3N', vagas_remanescentes_course: course },
  { name: 'POLO BARUERI – 5N', vagas_remanescentes_course: course },
  { name: 'POLO BARUERI – SM', vagas_remanescentes_course: course },
  { name: 'POLO CAPÃO BONITO – 5T', vagas_remanescentes_course: course },
  { name: 'POLO CRUZEIRO – 6T', vagas_remanescentes_course: course },
  { name: 'POLO DIADEMA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO DIADEMA – SM', vagas_remanescentes_course: course },
  { name: 'POLO ITAPETININGA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO ITAPETININGA – 4N', vagas_remanescentes_course: course },
  { name: 'POLO ITAPETININGA – SM', vagas_remanescentes_course: course },
  { name: 'POLO ITU – 6T', vagas_remanescentes_course: course },
  { name: 'POLO JALES – 6T', vagas_remanescentes_course: course },
  { name: 'POLO JALES – ST', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – 2N', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – SM', vagas_remanescentes_course: course },
  { name: 'POLO JUNDIAÍ – 4T', vagas_remanescentes_course: course },
  { name: 'POLO PINDAMONHANGABA – ST', vagas_remanescentes_course: course },
  { name: 'POLO SANTO ANDRÉ – 4T', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – 3N', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – 5N', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – PARQUE – 2N', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – PARQUE – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – PARQUE – SM', vagas_remanescentes_course: course },
  { name: 'POLO SÃO PAULO – ÁGUA AZUL – SM', vagas_remanescentes_course: course },
  { name: 'POLO SÃO PAULO – ÁGUA AZUL – ST', vagas_remanescentes_course: course },
  { name: 'POLO SÃO PAULO JAÇANÃ – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SÃO PAULO JAÇANÃ – SM', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Física I', vagas_remanescentes_course: course },
  { name: 'Informática', vagas_remanescentes_course: course },
  { name: 'Inglês', vagas_remanescentes_course: course },
  { name: 'Introdução à Engenharia', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Metodologia Científica', vagas_remanescentes_course: course },
  { name: 'Produção de Textos', vagas_remanescentes_course: course }
])

# ENGENHARIA DE COMPUTAÇÃO
course = VagasRemanescentesCourse.create(name: 'ENGENHARIA DE COMPUTAÇÃO')
VagasRemanescentesClass.create([
  { name: 'POLO ARARAS – 2N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – 5N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – ST', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO DIADEMA – SM', vagas_remanescentes_course: course },
  { name: 'POLO DIADEMA – ST', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – ST', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – 4N', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – SM', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – 2N', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – 2N', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – CASA BLANCA – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAÇANÃ – 3N', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAÇANÃ – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAÇANÃ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAMBEIRO – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAMBEIRO – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAMBEIRO – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SP – MENINOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – MENINOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – PERA MARMELO – 2N', vagas_remanescentes_course: course },
  { name: 'POLO SP – PERA MARMELO – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – PERA MARMELO – ST', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Circuitos Elétricos', vagas_remanescentes_course: course },
  { name: 'Circuitos Lógicos', vagas_remanescentes_course: course },
  { name: 'Eletrônica Aplicada', vagas_remanescentes_course: course },
  { name: 'Engenharia Econômica', vagas_remanescentes_course: course },
  { name: 'Estratégia e Planejamento de Empresas', vagas_remanescentes_course: course },
  { name: 'Estruturas de Dados', vagas_remanescentes_course: course },
  { name: 'Organização de Computadores', vagas_remanescentes_course: course },
  { name: 'Administração I', vagas_remanescentes_course: course },
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Cálculo II', vagas_remanescentes_course: course },
  { name: 'Cálculo III', vagas_remanescentes_course: course },
  { name: 'Ciência do Ambiente', vagas_remanescentes_course: course },
  { name: 'Ciência dos Materiais', vagas_remanescentes_course: course },
  { name: 'Economia', vagas_remanescentes_course: course },
  { name: 'Estatística', vagas_remanescentes_course: course },
  { name: 'Expressão Gráfica', vagas_remanescentes_course: course },
  { name: 'Fenômenos de Transporte', vagas_remanescentes_course: course },
  { name: 'Física I', vagas_remanescentes_course: course },
  { name: 'Física II', vagas_remanescentes_course: course },
  { name: 'Física III', vagas_remanescentes_course: course },
  { name: 'Geometria Analítica e Álgebra Linear', vagas_remanescentes_course: course },
  { name: 'Higiene e Segurança do Trabalho', vagas_remanescentes_course: course },
  { name: 'Informática', vagas_remanescentes_course: course },
  { name: 'Inglês', vagas_remanescentes_course: course },
  { name: 'Instalações Elétricas', vagas_remanescentes_course: course },
  { name: 'Introdução à Engenharia', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Mecânica Geral', vagas_remanescentes_course: course },
  { name: 'Metodologia Científica', vagas_remanescentes_course: course },
  { name: 'Métodos Numéricos', vagas_remanescentes_course: course },
  { name: 'Produção de Textos', vagas_remanescentes_course: course },
  { name: 'Programação de Computadores', vagas_remanescentes_course: course },
  { name: 'Química', vagas_remanescentes_course: course },
  { name: 'Resistência dos Materiais', vagas_remanescentes_course: course },
  { name: 'Sistemas de Informação', vagas_remanescentes_course: course },
  { name: 'Sociedade e Cultura', vagas_remanescentes_course: course }
])

# ENGENHARIA DE PRODUÇÃO
course = VagasRemanescentesCourse.create(name: 'ENGENHARIA DE PRODUÇÃO')
VagasRemanescentesClass.create([
  { name: 'POLO ARARAS – 2N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – 5N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – ST', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – 4N', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO DIADEMA – ST', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – SM', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – ST', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – 3N', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – 2N', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – CAMPO LIMPO – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SP – CAMPO LIMPO – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – CAMPO LIMPO – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – CIDADE DUTRA – 5N', vagas_remanescentes_course: course },
  { name: 'POLO SP – CIDADE DUTRA – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – CIDADE DUTRA – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – JAÇANÃ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – PARQUE SÃO CARLOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO ST – ROSA DA CHINA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO ST – ROSA DA CHINA – SM', vagas_remanescentes_course: course },
  { name: 'POLO ST – ROSA DA CHINA – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – VILA ATLÃNTICA – 3N', vagas_remanescentes_course: course },
  { name: 'POLO SP – VILA ATLÃNTICA – ST', vagas_remanescentes_course: course },
  { name: 'POLO TARUMÃ – 4N', vagas_remanescentes_course: course },
  { name: 'POLO TARUMÃ – SM', vagas_remanescentes_course: course },
  { name: 'POLO TARUMÃ – ST', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Confiabilidade', vagas_remanescentes_course: course },
  { name: 'Engenharia de Métodos', vagas_remanescentes_course: course },
  { name: 'Higiene e Segurança do Trabalho II', vagas_remanescentes_course: course },
  { name: 'Pesquisa Operacional I', vagas_remanescentes_course: course },
  { name: 'Pesquisa Operacional II', vagas_remanescentes_course: course },
  { name: 'Processos Industriais e Fabricação', vagas_remanescentes_course: course },
  { name: 'Psicologia e Sociologia do Trabalho', vagas_remanescentes_course: course },
  { name: 'Administração I', vagas_remanescentes_course: course },
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Cálculo II', vagas_remanescentes_course: course },
  { name: 'Cálculo III', vagas_remanescentes_course: course },
  { name: 'Ciência do Ambiente', vagas_remanescentes_course: course },
  { name: 'Ciência dos Materiais', vagas_remanescentes_course: course },
  { name: 'Economia', vagas_remanescentes_course: course },
  { name: 'Estatística', vagas_remanescentes_course: course },
  { name: 'Expressão Gráfica', vagas_remanescentes_course: course },
  { name: 'Fenômenos de Transporte', vagas_remanescentes_course: course },
  { name: 'Física I', vagas_remanescentes_course: course },
  { name: 'Física II', vagas_remanescentes_course: course },
  { name: 'Física III', vagas_remanescentes_course: course },
  { name: 'Geometria Analítica e Álgebra Linear', vagas_remanescentes_course: course },
  { name: 'Higiene e Segurança do Trabalho', vagas_remanescentes_course: course },
  { name: 'Informática', vagas_remanescentes_course: course },
  { name: 'Inglês', vagas_remanescentes_course: course },
  { name: 'Instalações Elétricas', vagas_remanescentes_course: course },
  { name: 'Introdução à Engenharia', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Mecânica Geral', vagas_remanescentes_course: course },
  { name: 'Metodologia Científica', vagas_remanescentes_course: course },
  { name: 'Métodos Numéricos', vagas_remanescentes_course: course },
  { name: 'Produção de Textos', vagas_remanescentes_course: course },
  { name: 'Programação de Computadores', vagas_remanescentes_course: course },
  { name: 'Química', vagas_remanescentes_course: course },
  { name: 'Resistência dos Materiais', vagas_remanescentes_course: course },
  { name: 'Sistemas de Informação', vagas_remanescentes_course: course },
  { name: 'Sociedade e Cultura', vagas_remanescentes_course: course }
])

# LICENCIATURA EM BIOLOGIA
course = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM BIOLOGIA')
VagasRemanescentesClass.create([
  { name: 'POLO ITAPETININGA – ST', vagas_remanescentes_course: course },
  { name: 'POLO JALES – SM', vagas_remanescentes_course: course },
  { name: 'POLO JUNDIAÍ – 6T', vagas_remanescentes_course: course },
  { name: 'POLO JUNDIAÍ – SM', vagas_remanescentes_course: course },
  { name: 'POLO MOCOCA – SM', vagas_remanescentes_course: course },
  { name: 'POLO MOCOCA – ST', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DOS CAMPOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO TARUMÃ – SM', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Bioquímica', vagas_remanescentes_course: course },
  { name: 'Células e Tecidos', vagas_remanescentes_course: course },
  { name: 'Corpo Humano: Órgãos e Sistemas', vagas_remanescentes_course: course },
  { name: 'Didática para Ciências e Biologia', vagas_remanescentes_course: course },
  { name: 'Inglês Va', vagas_remanescentes_course: course },
  { name: 'Inglês Vb', vagas_remanescentes_course: course },
  { name: 'Práticas para o Ensino de Ciências', vagas_remanescentes_course: course },
  { name: 'Zoologia dos Invertebrados', vagas_remanescentes_course: course },
  { name: 'Biologia Geral', vagas_remanescentes_course: course },
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Cultura Brasileira', vagas_remanescentes_course: course },
  { name: 'Educação e Inclusão Social', vagas_remanescentes_course: course },
  { name: 'Estatística', vagas_remanescentes_course: course },
  { name: 'Estudos da Atmosfera, Geosfera e Hidrosfera', vagas_remanescentes_course: course },
  { name: 'Filosofia da Educação', vagas_remanescentes_course: course },
  { name: 'Física Geral', vagas_remanescentes_course: course },
  { name: 'Fundamentos da Organização do Currículo Escolar', vagas_remanescentes_course: course },
  { name: 'História da Educação', vagas_remanescentes_course: course },
  { name: 'Inglês Ia', vagas_remanescentes_course: course },
  { name: 'Inglês Ib', vagas_remanescentes_course: course },
  { name: 'Inglês IIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIb', vagas_remanescentes_course: course },
  { name: 'Inglês IIIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIIb', vagas_remanescentes_course: course },
  { name: 'Inglês IVa', vagas_remanescentes_course: course },
  { name: 'Inglês IVb', vagas_remanescentes_course: course },
  { name: 'Legislação do Ensino', vagas_remanescentes_course: course },
  { name: 'Leitura e Produção de Textos', vagas_remanescentes_course: course },
  { name: 'Letramento Digital', vagas_remanescentes_course: course },
  { name: 'LIBRAS', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Meio Ambiente e Sustentabilidade', vagas_remanescentes_course: course },
  { name: 'Métodos para a Produção do Conhecimento', vagas_remanescentes_course: course },
  { name: 'Organização do Estado Brasileiro', vagas_remanescentes_course: course },
  { name: 'Políticas Públicas para a Educação', vagas_remanescentes_course: course },
  { name: 'Processos de Avaliação', vagas_remanescentes_course: course },
  { name: 'Psicologia da Aprendizagem', vagas_remanescentes_course: course },
  { name: 'Psicologia do Desenvolvimento', vagas_remanescentes_course: course },
  { name: 'Química Geral', vagas_remanescentes_course: course },
  { name: 'Sociedade, Tecnologia e Inovação', vagas_remanescentes_course: course },
  { name: 'Sociologia da Educação', vagas_remanescentes_course: course }
])


# LICENCIATURA EM FÍSICA
course = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM FÍSICA')
VagasRemanescentesClass.create([
  { name: 'POLO DIADEMA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO DIADEMA – SM', vagas_remanescentes_course: course },
  { name: 'POLO ITU – SM', vagas_remanescentes_course: course },
  { name: 'POLO ITU – ST', vagas_remanescentes_course: course },
  { name: 'POLO MOGI MIRIM – 6T', vagas_remanescentes_course: course },
  { name: 'POLO MOGI MIRIM – SM', vagas_remanescentes_course: course },
  { name: 'POLO OSASCO – SM', vagas_remanescentes_course: course },
  { name: 'POLO PINDAMONHANGABA – 6T', vagas_remanescentes_course: course },
  { name: 'POLO PINDAMONHANGABA – SM', vagas_remanescentes_course: course },
  { name: 'POLO SANTO ANDRÉ – 4T', vagas_remanescentes_course: course },
  { name: 'POLO SANTO ANDRÉ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DO RIO PRETO – SM', vagas_remanescentes_course: course },
  { name: 'POLO SÃO JOSÉ DO RIO PRETO – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – ÁGUA AZUL – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SP – JARDIM PAULISTANO – 5N', vagas_remanescentes_course: course },
  { name: 'POLO SP – JARDIM PAULISTANO – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – TATUAPÉ – 6T', vagas_remanescentes_course: course },
  { name: 'POLO SP – TATUAPÉ – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – TATUAPÉ – ST', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Cálculo II', vagas_remanescentes_course: course },
  { name: 'Didática para Ciências e Física', vagas_remanescentes_course: course },
  { name: 'Geometria Analítica', vagas_remanescentes_course: course },
  { name: 'Inglês Va', vagas_remanescentes_course: course },
  { name: 'Inglês Vb', vagas_remanescentes_course: course },
  { name: 'Mecânica', vagas_remanescentes_course: course },
  { name: 'Práticas para o Ensino de Ciências', vagas_remanescentes_course: course },
  { name: 'Biologia Geral', vagas_remanescentes_course: course },
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Cultura Brasileira', vagas_remanescentes_course: course },
  { name: 'Educação e Inclusão Social', vagas_remanescentes_course: course },
  { name: 'Estatística', vagas_remanescentes_course: course },
  { name: 'Estudos da Atmosfera, Geosfera e Hidrosfera', vagas_remanescentes_course: course },
  { name: 'Filosofia da Educação', vagas_remanescentes_course: course },
  { name: 'Física Geral', vagas_remanescentes_course: course },
  { name: 'Fundamentos da Organização do Currículo Escolar', vagas_remanescentes_course: course },
  { name: 'História da Educação', vagas_remanescentes_course: course },
  { name: 'Inglês Ia', vagas_remanescentes_course: course },
  { name: 'Inglês Ib', vagas_remanescentes_course: course },
  { name: 'Inglês IIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIb', vagas_remanescentes_course: course },
  { name: 'Inglês IIIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIIb', vagas_remanescentes_course: course },
  { name: 'Inglês IVa', vagas_remanescentes_course: course },
  { name: 'Inglês IVb', vagas_remanescentes_course: course },
  { name: 'Legislação do Ensino', vagas_remanescentes_course: course },
  { name: 'Leitura e Produção de Textos', vagas_remanescentes_course: course },
  { name: 'Letramento Digital', vagas_remanescentes_course: course },
  { name: 'LIBRAS', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Meio Ambiente e Sustentabilidade', vagas_remanescentes_course: course },
  { name: 'Métodos para a Produção do Conhecimento', vagas_remanescentes_course: course },
  { name: 'Organização do Estado Brasileiro', vagas_remanescentes_course: course },
  { name: 'Políticas Públicas para a Educação', vagas_remanescentes_course: course },
  { name: 'Processos de Avaliação', vagas_remanescentes_course: course },
  { name: 'Psicologia da Aprendizagem', vagas_remanescentes_course: course },
  { name: 'Psicologia do Desenvolvimento', vagas_remanescentes_course: course },
  { name: 'Química Geral', vagas_remanescentes_course: course },
  { name: 'Sociedade, Tecnologia e Inovação', vagas_remanescentes_course: course },
  { name: 'Sociologia da Educação', vagas_remanescentes_course: course }
])


# LICENCIATURA EM MATEMÁTICA
course = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM MATEMÁTICA')
VagasRemanescentesClass.create([
  { name: 'POLO ARARAS – 3N', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – SM', vagas_remanescentes_course: course },
  { name: 'POLO ARARAS – ST', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – 3N', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO BARRETOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO CAPÃO BONITO – SM', vagas_remanescentes_course: course },
  { name: 'POLO CAPÃO BONITO – ST', vagas_remanescentes_course: course },
  { name: 'POLO CRUZEIRO – SM', vagas_remanescentes_course: course },
  { name: 'POLO CRUZEIRO – ST', vagas_remanescentes_course: course },
  { name: 'POLO INDAIATUBA – SM', vagas_remanescentes_course: course },
  { name: 'POLO INDAIATUBA – ST', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – 4N', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – SM', vagas_remanescentes_course: course },
  { name: 'POLO JAÚ – ST', vagas_remanescentes_course: course },
  { name: 'POLO JUNDIAÍ – 6T', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SANTOS – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – PARQUE VEREDAS – 5N', vagas_remanescentes_course: course },
  { name: 'POLO SP – PARQUE VEREDAS – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – PARQUE VEREDAS – ST', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Cálculo II', vagas_remanescentes_course: course },
  { name: 'Cálculo Numérico', vagas_remanescentes_course: course },
  { name: 'Didática para o Ensino de Matemática', vagas_remanescentes_course: course },
  { name: 'Geometria Analítica', vagas_remanescentes_course: course },
  { name: 'Inglês Va', vagas_remanescentes_course: course },
  { name: 'Inglês Vb', vagas_remanescentes_course: course },
  { name: 'Mecânica', vagas_remanescentes_course: course },
  { name: 'Práticas para o Ensino de Matemática I', vagas_remanescentes_course: course },
  { name: 'Biologia Geral', vagas_remanescentes_course: course },
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Cultura Brasileira', vagas_remanescentes_course: course },
  { name: 'Educação e Inclusão Social', vagas_remanescentes_course: course },
  { name: 'Estatística', vagas_remanescentes_course: course },
  { name: 'Estudos da Atmosfera, Geosfera e Hidrosfera', vagas_remanescentes_course: course },
  { name: 'Filosofia da Educação', vagas_remanescentes_course: course },
  { name: 'Física Geral', vagas_remanescentes_course: course },
  { name: 'Fundamentos da Organização do Currículo Escolar', vagas_remanescentes_course: course },
  { name: 'História da Educação', vagas_remanescentes_course: course },
  { name: 'Inglês Ia', vagas_remanescentes_course: course },
  { name: 'Inglês Ib', vagas_remanescentes_course: course },
  { name: 'Inglês IIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIb', vagas_remanescentes_course: course },
  { name: 'Inglês IIIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIIb', vagas_remanescentes_course: course },
  { name: 'Inglês IVa', vagas_remanescentes_course: course },
  { name: 'Inglês IVb', vagas_remanescentes_course: course },
  { name: 'Legislação do Ensino', vagas_remanescentes_course: course },
  { name: 'Leitura e Produção de Textos', vagas_remanescentes_course: course },
  { name: 'Letramento Digital', vagas_remanescentes_course: course },
  { name: 'LIBRAS', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Meio Ambiente e Sustentabilidade', vagas_remanescentes_course: course },
  { name: 'Métodos para a Produção do Conhecimento', vagas_remanescentes_course: course },
  { name: 'Organização do Estado Brasileiro', vagas_remanescentes_course: course },
  { name: 'Políticas Públicas para a Educação', vagas_remanescentes_course: course },
  { name: 'Processos de Avaliação', vagas_remanescentes_course: course },
  { name: 'Psicologia da Aprendizagem', vagas_remanescentes_course: course },
  { name: 'Psicologia do Desenvolvimento', vagas_remanescentes_course: course },
  { name: 'Química Geral', vagas_remanescentes_course: course },
  { name: 'Sociedade, Tecnologia e Inovação', vagas_remanescentes_course: course },
  { name: 'Sociologia da Educação', vagas_remanescentes_course: course }
])

# LICENCIATURA EM QUÍMICA
course = VagasRemanescentesCourse.create(name: 'LICENCIATURA EM QUÍMICA')
VagasRemanescentesClass.create([
  { name: 'POLO ARAÇATUBA – 6T', vagas_remanescentes_course: course },
  { name: 'POLO ARAÇATUBA – ST', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – 2N', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – SM', vagas_remanescentes_course: course },
  { name: 'POLO FRANCA – ST', vagas_remanescentes_course: course },
  { name: 'POLO ITU – SM', vagas_remanescentes_course: course },
  { name: 'POLO ITU – ST', vagas_remanescentes_course: course },
  { name: 'POLO MOGI MIRIM – 6T', vagas_remanescentes_course: course },
  { name: 'POLO MOGI MIRIM – ST', vagas_remanescentes_course: course },
  { name: 'POLO OSASCO – 4M', vagas_remanescentes_course: course },
  { name: 'POLO OSASCO – SM', vagas_remanescentes_course: course },
  { name: 'POLO PINDAMONHANGABA – 6T', vagas_remanescentes_course: course },
  { name: 'POLO PINDAMONHANGABA – SM', vagas_remanescentes_course: course },
  { name: 'POLO SANTO ANDRÉ – 4T', vagas_remanescentes_course: course },
  { name: 'POLO SANTO ANDRÉ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – BUTANTÃ – 4N', vagas_remanescentes_course: course },
  { name: 'POLO SP – BUTANTÃ – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – BUTANTÃ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – TATUAPÉ – 6T', vagas_remanescentes_course: course },
  { name: 'POLO SP – TATUAPÉ – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – TATUAPÉ – ST', vagas_remanescentes_course: course },
  { name: 'POLO SP – VILA CURUÇÁ – 2N', vagas_remanescentes_course: course },
  { name: 'POLO SP – VILA CURUÇÁ – SM', vagas_remanescentes_course: course },
  { name: 'POLO SP – VILA CURUÇÁ – ST', vagas_remanescentes_course: course }
])
VagasRemanescentesActivity.create([
  { name: 'Cálculo e Geometria Analítica', vagas_remanescentes_course: course },
  { name: 'Didática para Ciências e Química', vagas_remanescentes_course: course },
  { name: 'Física Aplicada à Química', vagas_remanescentes_course: course },
  { name: 'Inglês Va', vagas_remanescentes_course: course },
  { name: 'Inglês Vb', vagas_remanescentes_course: course },
  { name: 'Práticas para o Ensino de Ciências', vagas_remanescentes_course: course },
  { name: 'Química Analítica', vagas_remanescentes_course: course },
  { name: 'Biologia Geral', vagas_remanescentes_course: course },
  { name: 'Cálculo I', vagas_remanescentes_course: course },
  { name: 'Cultura Brasileira', vagas_remanescentes_course: course },
  { name: 'Educação e Inclusão Social', vagas_remanescentes_course: course },
  { name: 'Estatística', vagas_remanescentes_course: course },
  { name: 'Estudos da Atmosfera, Geosfera e Hidrosfera', vagas_remanescentes_course: course },
  { name: 'Filosofia da Educação', vagas_remanescentes_course: course },
  { name: 'Física Geral', vagas_remanescentes_course: course },
  { name: 'Fundamentos da Organização do Currículo Escolar', vagas_remanescentes_course: course },
  { name: 'História da Educação', vagas_remanescentes_course: course },
  { name: 'Inglês Ia', vagas_remanescentes_course: course },
  { name: 'Inglês Ib', vagas_remanescentes_course: course },
  { name: 'Inglês IIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIb', vagas_remanescentes_course: course },
  { name: 'Inglês IIIa', vagas_remanescentes_course: course },
  { name: 'Inglês IIIb', vagas_remanescentes_course: course },
  { name: 'Inglês IVa', vagas_remanescentes_course: course },
  { name: 'Inglês IVb', vagas_remanescentes_course: course },
  { name: 'Legislação do Ensino', vagas_remanescentes_course: course },
  { name: 'Leitura e Produção de Textos', vagas_remanescentes_course: course },
  { name: 'Letramento Digital', vagas_remanescentes_course: course },
  { name: 'LIBRAS', vagas_remanescentes_course: course },
  { name: 'Matemática', vagas_remanescentes_course: course },
  { name: 'Meio Ambiente e Sustentabilidade', vagas_remanescentes_course: course },
  { name: 'Métodos para a Produção do Conhecimento', vagas_remanescentes_course: course },
  { name: 'Organização do Estado Brasileiro', vagas_remanescentes_course: course },
  { name: 'Políticas Públicas para a Educação', vagas_remanescentes_course: course },
  { name: 'Processos de Avaliação', vagas_remanescentes_course: course },
  { name: 'Psicologia da Aprendizagem', vagas_remanescentes_course: course },
  { name: 'Psicologia do Desenvolvimento', vagas_remanescentes_course: course },
  { name: 'Química Geral', vagas_remanescentes_course: course },
  { name: 'Sociedade, Tecnologia e Inovação', vagas_remanescentes_course: course },
  { name: 'Sociologia da Educação', vagas_remanescentes_course: course }
])
